### ISSUE TITLE
Source not compatible with windows file system

### ISSUE THREAD

**Issue by nidin** [MichaReiser/speedy.js#11]
Cannot checkout the source in windows machine due to special characters in the file name.

![image](https://cloud.githubusercontent.com/assets/198246/24786144/61eb49ce-1b5f-11e7-9d3b-d73d0f27510e.png)

```
Cloning into 'speedy.js'...
remote: Counting objects: 1253, done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 1253 (delta 67), reused 0 (delta 0), pack-reused 1107
Receiving objects: 100% (1253/1253), 468.16 KiB | 139.00 KiB/s, done.
Resolving deltas: 100% (751/751), done.
error: unable to create file packages/compiler/__tests__/code-generation/cases/binary-expression/**.ts: Invalid argument
error: unable to create file packages/compiler/__tests__/code-generation/cases/binary-expression/*.ts: Invalid argument
error: unable to create file packages/compiler/__tests__/code-generation/cases/binary-expression/<.ts: Invalid argument
error: unable to create file packages/compiler/__tests__/code-generation/cases/binary-expression/<=.ts: Invalid argument
error: unable to create file packages/compiler/__tests__/code-generation/cases/binary-expression/>.ts: Invalid argument
error: unable to create file packages/compiler/__tests__/code-generation/cases/binary-expression/>=.ts: Invalid argument
error: unable to create file packages/compiler/__tests__/code-generation/cases/binary-expression/|.ts: Invalid argument
error: unable to create file packages/compiler/__tests__/code-generation/cases/binary-expression/||.ts: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by MichaReiser** [comment]
Good Morning

I'm glad that you're interested in the project. I feared that the file names would not work on windows, but I still hoped they would. But I'm now going to change them (I hope I catch all of them).

You must know that the project is very pre-alpha and I never tested it on windows (that's also the reason why there is no readme). But if your interested and do not shy from the complications you might face then I'm willing to help you where ever I can. 

First of all, you need a custom build of LLVM. If you are lucky, then the install scripts in the preinstall step just work (but you need a C++ compiler). However, I might suggest that you [build llvm](http://llvm.org/docs/GettingStartedVS.html) on your own (there is also a GitHub repo where you can get the source). You can then set the path to your LLVM installation as environment variable before installation that will then be picked up (out of some reason, two variables have to be set)

```bash
export LLVM=/usr/bin
export GYP_DEFINES="LLVM_CONFIG=/usr/bin/llvm-config-5.0"
```
Are you the author of turboscript? You released your projects just weeks after I had more or less the same Ideas as you had. Either I lack the time. But my main goal is to link this project in a next step with [parallel-es](https://github.com/MichaReiser/parallel.es) to bring simply to use parallelization with true shared memory to JavaScript. Maybe we can share some insights and ideas?

**Comment by nidin** [comment]
Good morning,
I am also working towards the same goals compile TypeScript to WASM and easy parallel programming in JavaScript.

I am building it in Mac, let's see.

Yes, I am the author of turboscript. My implementation not yet using LLVM backend. I am thinking about emitting IR then feed it to LLVM to optimize. I am open to any discussions. first let me goes through the source code then compile and run some sample codes. I will definitely come back to you to share my findings. As the goal is same we could also work together to solve common problems.

**Comment by MichaReiser** [comment]
The llvm backend has the benefit, that the optimizer does great work and emitting IR code isn't that hard. However, it is a quite big dependency. I have seen that the WASM team also has an optimizer now. Maybe this one would be sufficient for your use case? 

I would be particularly interested in doing so after my master thesis. I have to do the master thesis on my own ;)

**Comment by nidin** [comment]
Yes LLVM backend is quite heavy. It may slow down the development but I have planned to implement LLVM IR emitter in the feature. for now baseline compiler is enough. 

I will keep an eye on your master thesis. 👀 :)

**Comment by nidin** [comment]
Between I failed to bootstrap in windows and mac. I will try it on Ubuntu once I extend the disk space, llvm eat all available space on my VM.
