### ISSUE TITLE
Create Test VM

### ISSUE THREAD

**Issue by MichaReiser** [MichaReiser/speedy.js#15]
Setup VM that can be used to experiment with the project

**Comment by MichaReiser** [comment]
Test VM is [available on mega](https://mega.nz/#!JHJzTYQa!zqC3JX1rGYybXfwPSNeSgPioF0rEyotj1QU4DR75OHs). 

user: speedyjs
password: welcome

Add to README.md

**Comment by nidin** [comment]
It was still failing, didn't get enough time to figure out the issue. I will try with image and let you know.

**Comment by nidin** [comment]
File is not downloadable since exceed free quota!

**Comment by MichaReiser** [comment]
Hmm.. I will try some other options. Let's see where I get a free space where I can host my file (or i have to switch to docker)

**Comment by MichaReiser** [comment]
Ok... I think I have found a way to host the files. I updated the link.

**Comment by MichaReiser** [comment]
Closed, VM is linked in README.md
