### ISSUE TITLE
Possible to Use Without LLVM?

### ISSUE THREAD

**Issue by chgibb** [MichaReiser/speedy.js#55]
This looks like an extremely promising project. However, the dependency on a source build of LLVM makes it nigh impossible to use in a CI/CD pipeline. Is there any way to get the speedy.js compiler to output ```wast``` directly, without LLVM or is the only target ```ll``` bitcode?

**Comment by MichaReiser** [comment]
Hy Chris

Im sorry, llvm is an essential part of the compiler. It is used to optimize
the program. Without it, speedy.js would be significant slower than
equvivalent js implementations.

Regarding CI. Take a look at the .travis.yml of this project. I have
prebuilt llvm in a linux vm and stored in a tar. The Build server downloads
and extracts the tar and sets LLVM_CONFIG to the path of the extracted
llvm-config binary.

I hope this helps.

Am 12.08.2017 10:39 nachm. schrieb "Chris Gibb" <notifications@github.com>:

**Comment by chgibb** [comment]
That helps a lot for Linux CI, though, would not quite work for Windows CI. My thought was, if Speedy.js can emit ```wast```, then I could use something like [Binaryen](https://github.com/WebAssembly/binaryen) to optimize and compile to ```wasm```.

**Comment by MichaReiser** [comment]
I believe this should also work for windows? You just need the binaries.
There is no need installing llvm

Am 13.08.2017 8:31 nachm. schrieb "Chris Gibb" <notifications@github.com>:

**Comment by chgibb** [comment]
I poked around the archive downloaded from running ```wget http://famreiser.ch/llvm/llvm-6.0-20170801.tar.gz``` from your ```.travis.yml```. It appears to contain only Linux binaries. Again, unfortunately of no use in a Windows CI scenario. Does Speedy.js only emit ```ll``` bitcode itself?

**Comment by MichaReiser** [comment]
The idea is that you build the binaries yourself on a dedicated machine.
These binaries can then be used on the ci

One part is to emit llvm ir, the other to generate the needed javascript
code to embed it into your application

Am 16.08.2017 5:46 nachm. schrieb "Chris Gibb" <notifications@github.com>:

**Comment by chgibb** [comment]
So the only things emitted directly by Speedy.js are LLVM IR and the associated Javascript glue?

**Comment by MichaReiser** [comment]
In the end it is a web assembly module and the javascript. But to do so, speedy uses llvm.
